server:
  port: 8081
  servlet:
    context-path: /index.html
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm
    username: sulaiman
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format-sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    view:
#      prefix: /templates, /static
#      suffix: /.html
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/, classpath:/templates/

